/// <reference types="astro/client" />

// Internal @astrojs/cloudflare paths used by src/worker.ts — resolved by Vite at
// build time but not exposed in the package.json exports map.
declare module '@astrojs/cloudflare/entrypoints/server.js' {
  export function createExports(manifest: unknown): { default: { fetch: (...args: unknown[]) => Promise<Response> } };
}

// worker-configuration.d.ts (generated by `wrangler types`) provides the
// global Env interface with all CF binding types (D1Database, KVNamespace, etc.)
// Augment it here with secrets and env vars not tracked in wrangler.toml.
interface Env {
  OPENAI_API_KEY?: string;
  APNS_KEY?: string;
  APNS_KEY_ID?: string;
  APNS_TEAM_ID?: string;
  APNS_BUNDLE_ID?: string;
  NOTIFICATION_QUEUE?: Queue;
}

type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

declare namespace App {
  interface Locals extends Runtime {
    cf?: Pick<
      IncomingRequestCfProperties,
      'city' | 'region' | 'country' | 'timezone' | 'colo' | 'latitude' | 'longitude'
    >;
  }
}
