/// <reference types="astro/client" />

// worker-configuration.d.ts (generated by `wrangler types`) provides the
// global Env interface with all CF binding types (D1Database, KVNamespace, etc.)
// Augment it here with secrets and env vars not tracked in wrangler.toml.
interface Env {
  OPENAI_API_KEY?: string;
  APNS_KEY?: string;
  APNS_KEY_ID?: string;
  APNS_TEAM_ID?: string;
  APNS_BUNDLE_ID?: string;
}

type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

declare namespace App {
  interface Locals extends Runtime {
    cf?: Pick<
      IncomingRequestCfProperties,
      'city' | 'region' | 'country' | 'timezone' | 'colo' | 'latitude' | 'longitude'
    >;
  }
}
